# Generated by Django 4.1.1 on 2022-09-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('person', models.IntegerField(default=0)),
                ('menu1', models.IntegerField(default=0)),
                ('menu2', models.IntegerField(default=0)),
                ('menu3', models.IntegerField(default=0)),
                ('menu4', models.IntegerField(default=0)),
                ('drink1', models.IntegerField(default=0)),
                ('drink2', models.IntegerField(default=0)),
                ('drink3', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
